USE FINANCEIRO
GO

IF SCHEMA_ID('cadastro') IS NULL
BEGIN
    EXEC('CREATE SCHEMA cadastro')
    PRINT 'SCHEMA CADASTRO CRIADO COM SUCESSO.'
END
GO

IF SCHEMA_ID('despesa') IS NULL
BEGIN
    EXEC('CREATE SCHEMA despesa')
    PRINT 'SCHEMA DESPESA CRIADO COM SUCESSO.'
END
GO

IF SCHEMA_ID('receita') IS NULL
BEGIN
    EXEC('CREATE SCHEMA receita')
    PRINT 'SCHEMA RECEITA CRIADO COM SUCESSO.'
END
GO

IF SCHEMA_ID('movimentacao') IS NULL
BEGIN
    EXEC('CREATE SCHEMA movimentacao')
    PRINT 'SCHEMA MOVIMENTACAO CRIADO COM SUCESSO.'
END
GO

IF SCHEMA_ID('regras') IS NULL
BEGIN
    EXEC('CREATE SCHEMA regras')
    PRINT 'SCHEMA REGRAS CRIADO COM SUCESSO.'
END
GO

GRANT EXECUTE ON SCHEMA :: cadastro TO AplicacaoRole
GO
GRANT EXECUTE ON SCHEMA :: despesa TO AplicacaoRole
GO
GRANT EXECUTE ON SCHEMA :: receita TO AplicacaoRole
GO
GRANT EXECUTE ON SCHEMA :: movimentacao TO AplicacaoRole
GO
GRANT EXECUTE ON SCHEMA :: regras TO AplicacaoRole
GO