USE master
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.syslogins WHERE name = 'aplicacao')
BEGIN
    CREATE LOGIN aplicacao WITH PASSWORD='aplicacao', CHECK_POLICY=OFF, CHECK_EXPIRATION=OFF
    PRINT 'LOGIN CRIADO COM SUCESSO.'
END
GO

USE FINANCEIRO
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.sysusers WHERE name = 'aplicacao')
BEGIN
    CREATE USER aplicacao FROM LOGIN aplicacao
    PRINT 'USUARIO CRIADO COM SUCESSO.'
END
GO