USE master
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.syslogins WHERE name = 'aplicacao')
BEGIN
    CREATE LOGIN aplicacao WITH PASSWORD='aplicacao', CHECK_POLICY=OFF, CHECK_EXPIRATION=OFF
END
GO

USE FINANCEIRO
GO

CREATE USER aplicacao FROM LOGIN aplicacao
GO